### PR TITLE
Add init package for image

### PR DESCRIPTION
**Pull request by davidsean**
Focal needs `init` package.

### CODE REVIEW

**Comment by ogra1** [comment]
looks fine 
I assume you have tested it with the existing older LTS versions (16.04, 18.04) as well ?
I'm not sure the init package is the same on all three ?

**Comment by davidsean** [comment]
I have not tested on earlier versions. I can do that now.

**Comment by davidsean** [comment]
Tried with LTS 18 and LTS 16 by changing to `FROM ubuntu:bionic` and `FROM ubuntu:xenial` (respectively).
The docker image builds and I can shell inside.
The containers have `ubuntu-image` installed as a snap.

I did not try signing a model or creating an image.

**Comment by ogra1** [comment]
nah, testing just the LTSes is fine (after all this set of scripts is focused on using and building snaps, which is only possible for/with the LTS releases) ... merging now ...

**Pull request merged**
